apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp-service-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idp-service-api
  template:
    metadata:
      labels:
        app: idp-service-api
    spec:
      containers:
        - name: idp-service-api
          image: silviugabor95/idp-service-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: idp-service-api-service
spec:
  selector:
    app: idp-service-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP