name: Build idp-service-api

on:
  workflow_dispatch: {}

jobs:
  build-idp-service-api:
    runs-on: ubuntu-latest
    environment: build_push

    steps:
      - name: Checkout todo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build idp-service-api
        run: ./gradlew :idp-service-api:clean :idp-service-api:build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build idp-service-api
        uses: docker/build-push-action@v4
        with:
          context: ./idp-service-api
          file: ./idp-service-api/Dockerfile
          push: true
          tags: >
            ${{ secrets.DOCKER_USERNAME }}/idp-service-api:latest