name: Deploy todo-api

on:
  workflow_dispatch:
    inputs:
      NGROK_HOST:
        description: 'k8s hostname'
        required: true
        default: '0.tcp.ngrok.io'
      NGROK_PORT:
        description: 'k8s port'
        required: true
        default: '12345'

jobs:
  deploy-todo-api:
    runs-on: ubuntu-latest
    environment: local

    env:
      NGROK_HOST: ${{ github.event.inputs.NGROK_HOST }}
      NGROK_PORT: ${{ github.event.inputs.NGROK_PORT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubeconfig from secret
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config

      - name: Test connection to Kubernetes
        run: kubectl cluster-info && kubectl get nodes

      - name: Deploy idp-service-api
        run: kubectl apply -f idp-service-api/idp-service-api.yaml

      - name: Verify Deployment Status
        run: |
          echo "Waiting for deployment to be ready..."
          kubectl wait --for=condition=available --timeout=300s deployment/idp-service-api-deployment || exit 1
          echo "Checking deployment status..."
          kubectl get deployment idp-service-api-deployment

      - name: Check Application Health
        run: |
          echo "Checking application health..."
          POD_NAME=$(kubectl get pods -l app=idp-service-api -o jsonpath="{.items[0].metadata.name}")
          if kubectl exec $POD_NAME -- wget -qO- http://localhost:8081/actuator/health | grep -q "UP"; then
            echo "✅ Application is healthy"
          else
            echo "❌ Health check failed"
            exit 1
          fi

      - name: Deploy todo-api
        run: kubectl apply -f todo-api/todo-api.yaml

      - name: Wait for Deployment Rollout
        run: kubectl rollout status deployment/todo-api-deployment --timeout=60s