name: Test Local Kubernetes via ngrok

on:
  workflow_dispatch:

jobs:
  test-k8s:
    runs-on: ubuntu-latest
    environment: local

    env:
      NGROK_HOST: 5.tcp.eu.ngrok.io
      NGROK_PORT: 10358
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubeconfig from secret
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config

      - name: Test connection to Kubernetes
        run: kubectl cluster-info && kubectl get nodes