name: Test Local Kubernetes via ngrok

on:
  workflow_dispatch:
    inputs:
      NGROK_HOST:
        description: 'Ngrok Host'
        required: true
        default: '0.tcp.ngrok.io'
      NGROK_PORT:
        description: 'Ngrok Port'
        required: true
        default: '12345'

jobs:
  test-k8s:
    runs-on: ubuntu-latest
    environment: local

    env:
      NGROK_HOST: ${{ github.event.inputs.NGROK_HOST }}
      NGROK_PORT: ${{ github.event.inputs.NGROK_PORT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubeconfig from secret
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config

      - name: Test connection to Kubernetes
        run: kubectl cluster-info && kubectl get nodes